services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: projeto-pricing-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}