version: '3'

services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: projeto-pricing-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - NODE_ENV=production
      # Variáveis do Supabase (substitua pelos valores reais)
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s 